version: '2'

services:
  data:
    build: .
    ports:
      - 8080:80
    volumes:
      - mods:/var/www/html/modules
      - profile:/var/www/html/profiles
      - theme:/var/www/html/themes
      - site:/var/www/html/sites

  sql:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: devops
    volumes:
      - sqldata:/var/lib/postgresql/data

volumes:
  sqldata:
  site:
  theme:
  profile:
  mods: