version: '2'

services:
  dt:
    image: drupal:8.8.2
    ports:
      - 8080:80
    volumes:
      - mods:/var/www/html/modules
      - profile:/var/www/html/profiles
      - theme:/var/www/html/themes
      - site:/var/www/html/sites

  postgres_sql:
    image: postgres:12.1
    environment:
      POSTGRES_PASSWORD: devops
    volumes:
      - sqldata:/var/lib/postgresql/data

volumes:
  mods:
  profile:
  theme:
  site:
  sqldata: